// All UI text strings used across the app.
// Admins can edit these via the Admin > Localizations panel.
// Keys are stored in the `localizations` table in Supabase.
// On first run, these defaults are seeded into the DB.

const strings = {
  // Brand
  'brand.name': 'Cubio',
  'brand.tagline': 'AI-Powered Business Automation',

  // Navigation
  'nav.dashboard': 'Dashboard',
  'nav.conversations': 'Conversations',
  'nav.business': 'Business Module',
  'nav.integrations': 'Integrations',
  'nav.settings': 'Settings',
  'nav.admin': 'Admin',
  'nav.signout': 'Sign Out',

  // Landing
  'landing.hero.badge': 'AI-Powered Sales Automation',
  'landing.hero.title': 'AI-Powered Business Automation Platform',
  'landing.hero.subtitle': 'Cubio streamlines your business operations with intelligent automation. Manage inventory, track leads, and automate customer communication 24/7.',
  'landing.hero.cta': 'Get Started',
  'landing.benefits.title': 'Why Businesses Choose Cubio',
  'landing.benefits.subtitle': 'Streamline your operations with intelligent automation',
  'landing.benefit1.title': 'Instant Responses',
  'landing.benefit1.desc': 'AI agents respond to every customer inquiry immediately, ensuring no opportunity is lost',
  'landing.benefit2.title': '24/7 Availability',
  'landing.benefit2.desc': 'Never miss inquiries after hours. Your AI assistant works around the clock',
  'landing.benefit3.title': 'Smart Automation',
  'landing.benefit3.desc': 'Automatically manage inventory, track leads, and qualify customers based on your criteria',
  'landing.benefit4.title': 'Higher Efficiency',
  'landing.benefit4.desc': 'Focus your team on high-value tasks while AI handles routine operations',
  'landing.businesses.title': 'Built for Your Industry',
  'landing.businesses.subtitle': 'Cubio adapts to your specific business type with tailored AI workflows',
  'landing.cta.title': 'Ready to Transform Your Business?',
  'landing.cta.subtitle': 'Join leading businesses using AI to automate their operations and boost efficiency',
  'landing.cta.button': 'Start Free Today',
  'landing.footer.copy': '© 2026 Cubio. All rights reserved.',

  // Auth
  'auth.login.title': 'Welcome to Cubio',
  'auth.login.subtitle': 'Sign in to your account',
  'auth.login.email': 'Email Address',
  'auth.login.password': 'Password',
  'auth.login.remember': 'Remember me',
  'auth.login.forgot': 'Forgot password?',
  'auth.login.submit': 'Sign In',
  'auth.login.submitting': 'Signing in...',
  'auth.login.no_account': "Don't have an account?",
  'auth.login.register_link': 'Create one',
  'auth.login.back': 'Back to home',
  'auth.register.title': 'Create your account',
  'auth.register.subtitle': 'Start automating your business today',
  'auth.register.name': 'Full Name',
  'auth.register.company': 'Company Name',
  'auth.register.email': 'Email Address',
  'auth.register.password': 'Password',
  'auth.register.confirm': 'Confirm Password',
  'auth.register.submit': 'Create Account',
  'auth.register.submitting': 'Creating account...',
  'auth.register.has_account': 'Already have an account?',
  'auth.register.login_link': 'Sign in',
  'auth.forgot.title': 'Forgot Password',
  'auth.forgot.subtitle': 'Enter your email and we will send you a reset link',
  'auth.forgot.email': 'Email Address',
  'auth.forgot.submit': 'Send Reset Link',
  'auth.forgot.submitting': 'Sending...',
  'auth.forgot.back': 'Back to login',
  'auth.forgot.success': 'Check your email for the reset link',
  'auth.error.invalid': 'Invalid email or password',
  'auth.error.generic': 'Something went wrong. Please try again.',
  'auth.error.email_taken': 'Email already registered',
  'auth.error.weak_password': 'Password must be at least 8 characters',
  'auth.error.password_mismatch': 'Passwords do not match',

  // Onboarding
  'onboarding.title': 'Select Your Business Profile',
  'onboarding.subtitle': 'Choose the profile that best matches your business',
  'onboarding.realestate.title': 'Real Estate Development Company',
  'onboarding.realestate.desc': 'Manage projects, apartments, leads, and AI-powered sales automation',
  'onboarding.realestate.f1': 'Projects Management',
  'onboarding.realestate.f2': 'Apartments Catalog',
  'onboarding.realestate.f3': 'Lead Tracking',
  'onboarding.realestate.f4': 'AI Sales Agent',
  'onboarding.crafts.title': 'Birthstone Crafts Shop',
  'onboarding.crafts.desc': 'Manage product catalog, birthstone jewelry, and zodiac compatibility',
  'onboarding.crafts.f1': 'Product Catalog',
  'onboarding.crafts.f2': 'Birthstone Management',
  'onboarding.crafts.f3': 'Zodiac Compatibility',
  'onboarding.crafts.f4': 'Inventory Tracking',
  'onboarding.confirm.title': 'Confirm Your Selection',
  'onboarding.confirm.warning': 'Changing business type later may archive existing business data. This selection will configure your dashboard and features.',
  'onboarding.confirm.back': 'Go Back',
  'onboarding.confirm.proceed': 'Yes, Confirm Selection',

  // Dashboard
  'dashboard.overview.title': 'Dashboard Overview',
  'dashboard.overview.subtitle': 'Monitor your business performance and AI agent activity',
  'dashboard.overview.total_leads': 'Total Leads',
  'dashboard.overview.vacant': 'Vacant Units',
  'dashboard.overview.reserved': 'Reserved',
  'dashboard.overview.sold': 'Sold',
  'dashboard.overview.total_products': 'Total Products',
  'dashboard.overview.ai_conversations': 'AI Conversations',
  'dashboard.overview.recent_leads': 'Recent Lead Activity',
  'dashboard.overview.view_all': 'View All',
  'dashboard.overview.ai_handled': 'AI Handled',

  // Projects
  'projects.title': 'Projects',
  'projects.subtitle': 'Manage your real estate development projects',
  'projects.add': 'Add Project',
  'projects.empty': 'No projects yet. Create your first project.',
  'projects.form.name': 'Project Name',
  'projects.form.location': 'Location',
  'projects.form.completion': 'Completion Date',
  'projects.form.status': 'Status',
  'projects.form.floors': 'Total Floors',
  'projects.form.description': 'Description',
  'projects.form.cover': 'Cover Image',
  'projects.form.save': 'Save Project',
  'projects.form.cancel': 'Cancel',
  'projects.status.planning': 'Planning',
  'projects.status.construction': 'Under Construction',
  'projects.status.completed': 'Completed',
  'projects.delete.confirm': 'Are you sure you want to delete this project? All apartments will also be deleted.',

  // Apartments
  'apartments.title': 'Apartments',
  'apartments.subtitle': 'Manage your apartment inventory',
  'apartments.add_single': 'Add Apartment',
  'apartments.add_bulk': 'Bulk Add',
  'apartments.add_template': 'Templates',
  'apartments.empty': 'No apartments yet.',
  'apartments.filter.all': 'All',
  'apartments.filter.status': 'Status',
  'apartments.filter.project': 'Project',
  'apartments.filter.floor': 'Floor',
  'apartments.status.vacant': 'Vacant',
  'apartments.status.reserved': 'Reserved',
  'apartments.status.sold': 'Sold',
  'apartments.form.number': 'Apartment Number',
  'apartments.form.project': 'Project',
  'apartments.form.size': 'Size (sq.m)',
  'apartments.form.floor': 'Floor',
  'apartments.form.rooms': 'Rooms',
  'apartments.form.price_sqm': 'Price per sq.m',
  'apartments.form.total_price': 'Total Price',
  'apartments.form.status': 'Status',
  'apartments.form.description': 'Description',
  'apartments.form.template': 'Use Template',
  'apartments.bulk.template': 'Template',
  'apartments.bulk.project': 'Project',
  'apartments.bulk.start_floor': 'Start Floor',
  'apartments.bulk.end_floor': 'End Floor',
  'apartments.bulk.units_per_floor': 'Units per Floor',
  'apartments.bulk.price_adj': 'Price Adjustment per Floor (%)',
  'apartments.template.name': 'Template Name',
  'apartments.template.size': 'Size (sq.m)',
  'apartments.template.rooms': 'Rooms',
  'apartments.template.price_sqm': 'Price per sq.m',
  'apartments.delete.confirm': 'Delete this apartment? This action cannot be undone.',

  // Products
  'products.title': 'Products',
  'products.subtitle': 'Manage your birthstone crafts catalog',
  'products.add': 'Add Product',
  'products.empty': 'No products yet. Add your first product.',
  'products.form.name': 'Product Name',
  'products.form.description': 'Description',
  'products.form.birthstones': 'Birthstones (comma separated)',
  'products.form.zodiac': 'Zodiac Compatibility',
  'products.form.price': 'Price',
  'products.form.save': 'Save Product',
  'products.form.cancel': 'Cancel',
  'products.delete.confirm': 'Delete this product?',

  // Conversations
  'conversations.title': 'Conversations',
  'conversations.subtitle': 'AI-managed customer conversations',
  'conversations.empty': 'No conversations yet.',
  'conversations.search': 'Search conversations...',
  'conversations.filter.all': 'All',
  'conversations.filter.open': 'Open',
  'conversations.filter.closed': 'Closed',
  'conversations.ai_handled': 'AI',
  'conversations.send': 'Send',
  'conversations.placeholder': 'Type a message...',

  // Integrations
  'integrations.title': 'Integrations',
  'integrations.subtitle': 'Connect your messaging channels',
  'integrations.add': 'Add Integration',
  'integrations.empty': 'No integrations configured. Contact admin to set up channels.',
  'integrations.provider': 'Provider',
  'integrations.account_name': 'Account Name',
  'integrations.account_id': 'Account ID',
  'integrations.status': 'Status',
  'integrations.active': 'Active',
  'integrations.inactive': 'Inactive',

  // Settings
  'settings.title': 'Settings',
  'settings.profile.title': 'Profile Settings',
  'settings.profile.name': 'Full Name',
  'settings.profile.email': 'Email',
  'settings.profile.save': 'Save Changes',
  'settings.company.title': 'Company Settings',
  'settings.company.name': 'Company Name',
  'settings.company.ai_enabled': 'AI Automation Enabled',
  'settings.company.save': 'Save Company',
  'settings.password.title': 'Change Password',
  'settings.password.current': 'Current Password',
  'settings.password.new': 'New Password',
  'settings.password.confirm': 'Confirm New Password',
  'settings.password.save': 'Update Password',

  // Admin
  'admin.title': 'Admin Panel',
  'admin.subtitle': 'Manage users, localizations, and integrations',
  'admin.tabs.users': 'Users',
  'admin.tabs.localizations': 'Localizations',
  'admin.tabs.integrations': 'Integrations',
  'admin.users.email': 'Email',
  'admin.users.company': 'Company',
  'admin.users.name': 'Full Name',
  'admin.users.business_type': 'Business Type',
  'admin.users.admin_status': 'Admin',
  'admin.users.created': 'Created',
  'admin.users.is_admin': 'Admin',
  'admin.users.is_user': 'User',
  'admin.loc.keyword': 'Keyword',
  'admin.loc.text': 'Text',
  'admin.loc.add': 'Add Localization',
  'admin.loc.save': 'Save',
  'admin.loc.delete.confirm': 'Delete this localization?',
  'admin.integrations.company': 'Company',
  'admin.integrations.provider': 'Provider',
  'admin.integrations.account_id': 'Account / Page ID',
  'admin.integrations.account_name': 'Account / Page Name',
  'admin.integrations.token': 'Access Token',
  'admin.integrations.refresh_token': 'Refresh Token (optional)',
  'admin.integrations.active': 'Active',
  'admin.integrations.save': 'Save Integration',
  'admin.integrations.delete.confirm': 'Delete this integration?',

  // Common
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.edit': 'Edit',
  'common.delete': 'Delete',
  'common.add': 'Add',
  'common.close': 'Close',
  'common.loading': 'Loading...',
  'common.error': 'Something went wrong.',
  'common.success': 'Saved successfully.',
  'common.search': 'Search...',
  'common.no_results': 'No results found.',
  'common.view_grid': 'Grid View',
  'common.view_list': 'List View',
  'common.confirm_delete': 'Are you sure?',
  'common.yes': 'Yes',
  'common.no': 'No',
  'common.actions': 'Actions',
  'common.status': 'Status',
  'common.created_at': 'Created',
  'common.updated_at': 'Updated',
} as const;

export type StringKey = keyof typeof strings;

// Runtime: fetch overrides from Supabase localizations table (server-side)
// For client components, use the `useStrings` hook from context
export function t(key: StringKey): string {
  return strings[key] ?? key;
}

export { strings as defaultStrings };
